import React, { useState, useEffect } from 'react';
import { ArrowUpRight, ArrowDownRight } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const sampleData = [
  { name: 'Mon', earnings: 400 },
  { name: 'Tue', earnings: 600 },
  { name: 'Wed', earnings: 500 },
  { name: 'Thu', earnings: 700 },
  { name: 'Fri', earnings: 800 },
  { name: 'Sat', earnings: 650 },
  { name: 'Sun', earnings: 900 },
];

const StatCard = ({ title, value, percent, increase }) => (
  <div className="bg-white p-4 rounded-xl shadow flex justify-between items-center">
    <div>
      <h4 className="text-sm text-gray-500">{title}</h4>
      <div className="text-xl font-bold">${value}</div>
    </div>
    <div className={`flex items-center text-sm font-semibold ${increase ? 'text-green-600' : 'text-red-600'}`}>
      {increase ? <ArrowUpRight className="w-4 h-4 mr-1" /> : <ArrowDownRight className="w-4 h-4 mr-1" />}
      {percent}%
    </div>
  </div>
);

export default function AdminDashboard() {
  const [range, setRange] = useState('week');
  const [branch, setBranch] = useState('All');
  const [data, setData] = useState(sampleData);

  useEffect(() => {
    // Simulated fetch call
    // fetch(`/api/analytics?range=${range}&branch=${branch}`)
    //   .then(res => res.json())
    //   .then(setData);
  }, [range, branch]);

  const navLinks = [
    'Dashboard', 'Orders', 'Sales', 'Users', 'Employees', 'Attendance', 'Stock Management',
    'Suppliers', 'Purchases', 'Menu', 'Menu Items', 'Tables', 'Reports', 'Settings'
  ];

  return (
    <div className="flex min-h-screen bg-gray-100">
      {/* Sidebar */}
      <aside className="w-64 bg-white shadow p-6 space-y-6 overflow-y-auto">
        <div className="flex items-center gap-3">
          <img
            src="https://i.pravatar.cc/50"
            alt="avatar"
            className="w-10 h-10 rounded-full"
          />
          <div>
            <div className="font-semibold text-gray-800">Admin Hannah</div>
            <div className="text-sm text-gray-500">Manager</div>
          </div>
        </div>
        <nav className="space-y-2">
          {navLinks.map(link => (
            <a key={link} href="#" className="block text-gray-700 hover:text-blue-600">{link}</a>
          ))}
        </nav>
      </aside>

      {/* Main */}
      <main className="flex-1 p-8 space-y-8">
        <h1 className="text-2xl font-bold text-gray-800">Dashboard Overview</h1>

        {/* Filters */}
        <div className="flex gap-4">
          <select
            value={range}
            onChange={(e) => setRange(e.target.value)}
            className="p-2 rounded border"
          >
            <option value="week">This Week</option>
            <option value="month">This Month</option>
          </select>
          <select
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            className="p-2 rounded border"
          >
            <option>All</option>
            <option>Downtown</option>
            <option>Uptown</option>
          </select>
        </div>

        {/* Stat Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <StatCard title="Today's Earnings" value="850" percent={12.5} increase={true} />
          <StatCard title="Orders" value="120" percent={-4.2} increase={false} />
          <StatCard title="New Customers" value="23" percent={6.8} increase={true} />
        </div>

        {/* Graph */}
        <div className="bg-white p-6 rounded-xl shadow">
          <h2 className="text-lg font-semibold mb-4">Earnings This {range === 'week' ? 'Week' : 'Month'}</h2>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={data}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Line type="monotone" dataKey="earnings" stroke="#3b82f6" strokeWidth={2} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        {/* Activity Feed */}
        <div className="bg-white p-6 rounded-xl shadow">
          <h2 className="text-lg font-semibold mb-4">Recent Activity</h2>
          <ul className="space-y-2 text-sm text-gray-700">
            <li>✅ Order #1023 placed by Sarah</li>
            <li>👤 New customer James registered</li>
            <li>📦 Inventory updated for Drinks</li>
            <li>🧾 Report generated by Admin</li>
            <li>💼 New supplier contract signed</li>
            <li>🍽️ Menu item "Grilled Fish" updated</li>
            <li>📅 Attendance recorded for Staff ID #201</li>
          </ul>
        </div>
      </main>
    </div>
  );
} //add lighmode to this